[package]
name = "crowd_pass"
description = "A ticketing platform on Starknet"
version = "0.0.200"
edition = "2024_07"
authors = [
    "David Dada <daveproxy80@gmail.com>",
    "Manoah Luka <manoahluka@gmail.com>",
    "Olorunsogo Banwo <sogobanwo@gmail.com>",
    "Olwakemi Atoyebi <atokemmy@gmail.com>",
]
homepage = "https://www.crowdpass.live/"
cairo_version = "2.8.5"
keywords = ["crowdpass", "event", "cairo", "contracts", "starknet", "standards"]

[dependencies]
starknet = "2.11.4"
openzeppelin = "2.0.0"
token_bound_accounts = { git = "https://github.com/DADADAVE80/Starknet-TBA" }
alexandria_data_structures = "0.5.1"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.45.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.voyager]
event_factory = { path = "event_factory/event_factory.cairo" }
ticket_721 = { path = "tickets/ticket_721.cairo" }

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
block_id.tag = "latest"

[[tool.snforge.fork]]
name = "MAINNET_LATEST"
# url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_8"
url = "https://starknet-mainnet.blastapi.io/1db11f5e-51a8-453a-8a6f-36d6e5cf49cd/rpc/v0_8"
block_id.tag = "latest"

[profile.dev.cairo]                                        # Configure Cairo compiler
unstable-add-statements-code-locations-debug-info = true   # Should be used if you want to use coverage
unstable-add-statements-functions-debug-info = true        # Should be used if you want to use coverage/profiler
inlining-strategy = "avoid"                                # Should be used if you want to use coverage

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

# Visit https://foundry-rs.github.io/starknet-foundry/appendix/scarb-toml.html for more information

# [tool.snforge]                                             # Define `snforge` tool section
# exit_first = true                                          # Stop tests execution immediately upon the first failure
# fuzzer_runs = 1234                                         # Number of runs of the random fuzzer
# fuzzer_seed = 1111                                         # Seed for the random fuzzer

# [[tool.snforge.fork]]
# name = "SOME_SECOND_NAME"
# url = "http://your.second.rpc.url"                         
# block_id.number = "123"                                    # Block to fork from (block number)

# [[tool.snforge.fork]]
# name = "SOME_THIRD_NAME"
# url = "http://your.third.rpc.url"
# block_id.hash = "0x123"                                    # Block to fork from (block hash)

# [features]                                                 # Used for conditional compilation
# enable_for_tests = []                                      # Feature name and list of other features that should be enabled with it
